config/routes.rb
ResearchHelper2::Application.routes.draw do
  
  get "articles/async_process" => "articles#async_process"
  
  resources :logs

  resources :genres

  resources :memos

  resources :articles

  root :to => "articles#index"
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :memo
  belongs_to :genre
  
end

app/controllers/articles_controller.rb
require 'basics'
include BASICS

class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    #--------------------------
    # Steps
    # 1. Get genre id from params
    # 1-2. Get sort_type from params
    # 2. Get articles
    #--------------------------

    #--------------------------
    # 1. Get genre id
    #--------------------------    
    # @genre_id = params[:genre_id]
    if params[:genre]
        @genre_id = params[:genre][:id]
    else
        @genre_id = nil
    end
    
    if @genre_id != nil and BASICS.is_numeric?(@genre_id)
        genre_id = @genre_id.to_i
    else
        genre_id = nil
    end
    
    @params = params
    
    #--------------------------
    # 1-2. Get sort_type from params
    #--------------------------
    @sort_type = params[:sort_type]
    
    if @sort_type == nil
      @sort_type = "id"
    end
    
    #--------------------------
    # 2. Get articles
    #--------------------------
    @id_all = Genre.find_by_name("ALL")
    
    if @id_all.id.to_i == genre_id    #=> Select all items
      # @articles = Article.all
      @articles = Article.find(:all, :order => @sort_type)
    elsif genre_id          #=> Select by genre id
      # @articles = Article.find_all_by_genre_id(genre_id)
      # @articles = Article.find(:all, :genre_id => genre_id, :order => @sort_type)
      # @articles = Article.find_by_genre_id(:all, :order => @sort_type)
      @articles = Article.find_all_by_genre_id(genre_id, :order => @sort_type)
    else
      # @articles = Article.all
      @articles = Article.find(:all, :order => @sort_type)
    end#if @id_all.id.to_i == genre_id
  
    # session[:articles] = @articles    #=> ActionDispatch::Cookies::CookieOverflow in ArticlesController#index
            
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end#def index

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    @memos = Memo.find_all_by_article_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  def async_process
    
    @time = Time.now.to_s
    
    render :partial => 'async_current'
    # render text: "abcde"
    # render text: @time = Time.now.to_s
    # render text: Genre.all.first.name
    
    
    # @time = Time.now.to_s
#     
    # respond_to do |format|
      # # format.html { redirect_to articles_url }
      # format.js
      # format.json { head :no_content }
    # end
  end#def async_process

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_async_current.html.erb
<%= @time %><br/>
<%= link_to 'Genres', genres_path %><br />

<input type="button" value="test2" onclick="test2()" /><br/>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :genre_id %><br />
    <%#= f.number_field :genre_id %>
    <%= select("article", "genre_id", Genre.all.collect {|g| [g.name, g.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/async_process.js.erb
$('#async').html(
	"<%= escape_javascript(render (:partial => 'async_current')) %>"
	
);

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div id="top"></div>
<div>
	<span class="page_title">
		記事のリスト
	</span>
	
	&nbsp;&nbsp;(<%= link_to 'New Article', new_article_path %>)
	
		&nbsp;<%= link_to 'To bottom', "#bottom" %>
		
</div>

<hr />
	<dl class="accordion">
		<dt>
			<span style="color: green">Admin data</span>
		</dt>
	
		<dd>
			@genre_id => <%= @genre_id %>
			<br />
			
			@genre_id.class => <%= @genre_id.class %>
			<br />
			
			@params => <%= @params %>
			<br />
			
			@params[:genre] => <%= @params[:genre] %>
			<br />
			
			<% if @params[:genre] %>
				@params[:genre][:id] => <%= @params[:genre][:id] %>
				<br />
				
				@params[:genre][:id].class => <%= @params[:genre][:id].class %>
				<br />
			<% else %>
				@params[:genre][:id] => nil
				<br />
				
				@params[:genre][:id].class => nil
				<br />
			<% end %>
			
			@id_all => <%= @id_all %>
			<br />
			
			@id_all.name => <%= @id_all.name %>
			<br />
			
			@id_all.id => <%= @id_all.id %>
			<br />
			
			@sort_type => <%= @sort_type %>
			<br />

		</dd>
	</dl>
<hr />

<table>
  <tr>
  	<th>
  		<%= link_to "Id", :controller => 'articles', :action => 'index', :sort_type => 'id' %>
  		
  	</th>
    <th>
    	<%= link_to "Title", :controller => 'articles', :action => 'index', :sort_type => 'title' %>
    	
	</th>
    <th>Text</th>
    <th>Memos</th>
    <th>Url</th>
    <th>
		<!--  REF => NewsReader2\app\views\categories\_form.html.erb -->
		<%#= form_tag('articles?sort_type=genre', :method => :get) do %>
		<%#= form_tag('', :method => :get, :sort_type => 'genre') do %>
			<%#= submit_tag "Genre" %>
			<%#= submit_tag "Genre", :sort_type => 'genre' %>
		<%# end %>
		<%#= link_to "Genre", articles_path, :sort_type => 'genre' %>
		<%#= link_to "Genre", :controller => 'articles', :action => 'index', :sort_type => 'genre' %>
		<%= link_to "Genre", :controller => 'articles', :action => 'index', :sort_type => 'genre_id' %>
		
		<%= form_tag('', :method => :get) do %>
			<%= select("genre", "id", Genre.all.collect {|g| [g.name, g.id]}, {:name => "genre_id"})%>
			
			<%#= select("genre", "id", Genre.all.collect {|g| [g.id, g.name]})%>
			<%= submit_tag "Go" %>
		    
		<% end %>
	</th>
  </tr>

<% @articles.each do |article| %>
  <tr>
  	<td><%= article.id %></td>
    <td><%= link_to article.title, article %></td>
<!--     <td><%#= article.text %></td> -->
    <td><%= truncate(article.text, length: 40) %></td>
    <td><%= article.memo.size %></td>
    
    <td><%= link_to "Go", article.url %></td>
    
    <% if article.genre != nil %>
    	<td><%= article.genre.name %> (<%= article.genre.id %>)</td>
    <% else %>
		<td>No entry</td>
	<% end %>
	
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>
&nbsp;| <%= link_to 'To top', "#top" %>


<div id="bottom"></div>
<%#= article.url %>

<hr/>

<!-- REF => 山田: 360 -->

<span id="async"><%= Time.now %></span>
<%#= link_to 'Update', {:action => 'async_process'}, :remote => true %>
<%= button_to 'Update(remote)', {:action => 'async_process'}, :remote => true %>
<%= button_to 'Update', {:action => 'async_process'}, :method => 'get' %>
<br />

<input type="button" value="Ajax" onclick="test1()" /><br/>


<!-- REF=> http://stackoverflow.com/questions/5441518/onclick-doesnt-work-in-button-to -->
<!-- REF=> http://www.ruby-forum.com/topic/12118 -->
<%= button_to "Ajax(button_to)", "javascript:test2()" %><br />

<!-- REF => http://guides.rubyonrails.org/ajax_on_rails.html#hello-ajax-a-quick-intro -->
<%= button_to "Index", {:action => "index", :genre => 'history'}, :remote => true, :form => { "data-type" => "json" } %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Text:</b>
  <%= @article.text %>
</p>

<p>
  <b>Url:</b>
  <%#= @article.url %>
  <%= link_to truncate(@article.url, length:40), @article.url, {:target => "_blank"} %>
</p>

<p>
  <b>Genre:</b>
  <%#= @article.url %>
	<% if @article.genre != nil %>
  		<%= @article.genre.id %>
	<% else %>
		No entry
	<% end %>
</p>

<p>
  <b>Memos:</b><br />
  <% if @memos.length > 0 %>
  	<% @memos.each_with_index do |memo, i| %>
  		<span style="color: green;">------------</span> 
  						Memo <%= i + 1 %>
		 <span style="color: green;">--------------</span>
		<br />		 
  		<%= memo.text %><br />
  	<% end %>
  <% else %>
  	No memo
  <% end %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>&nbsp;&nbsp;|&nbsp;
<!-- <%#= link_to 'Add memo', new_memo_path, :article_id => @article.id %>&nbsp;&nbsp;|&nbsp; -->
<%= link_to 'Add memo', 
    				:controller => "memos", :action => "new", 
    				:article_id => @article.id %>&nbsp;&nbsp;|&nbsp;
<%= link_to 'Destroy', @article, confirm: 'Are you sure?', method: :delete, style: "color: red;" %>

<!-- <br /> -->
<%#= @memos.class %>
<%#= @memos.length %>
<%#= truncate(@article.url, length:40) %>

app/views/articles/show_accordion~1.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Text:</b>
  <%= @article.text %>
</p>

<p>
  <b>Url:</b>
  <%#= @article.url %>
  <%= link_to truncate(@article.url, length:40), @article.url, {:target => "_blank"} %>
</p>

<p>
  <b>Genre:</b>
  <%#= @article.url %>
	<% if @article.genre != nil %>
  		<%= @article.genre.id %>
	<% else %>
		No entry
	<% end %>
</p>

<p>
  <!-- <b>Memos:</b><br /> -->
  <dl class="accordion"><b>Memos:</b><br />
  
	  <% if @memos.length > 0 %>
	  	<% @memos.each_with_index do |memo, i| %>
	  		<% if i == -1 %>
	  			<dt class="opened">
			<% else %>
				<dt>
			<% end %>
	  			<span style="color: green;">------------</span> 
					<%= i + 1 %>
			 	<span style="color: green;">--------------</span>
			 </dt>
			 
			<br />
			
			<dd>	 
	  			<%= memo.text %>
	  		</dd>
	  		
	  		<br />
	  		
	  	<% end %>
	  <% else %>
	  	No memo
	  <% end %>
	</dl>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>&nbsp;&nbsp;|&nbsp;
<!-- <%#= link_to 'Add memo', new_memo_path, :article_id => @article.id %>&nbsp;&nbsp;|&nbsp; -->
<%= link_to 'Add memo', 
    				:controller => "memos", :action => "new", 
    				:article_id => @article.id %>&nbsp;&nbsp;|&nbsp;
<%= link_to 'Destroy', @article, confirm: 'Are you sure?', method: :delete, style: "color: red;" %>

<!-- <br /> -->
<%#= @memos.class %>
<%#= @memos.length %>
<%#= truncate(@article.url, length:40) %>

app/views/articles/show~up_to_pre_accordion.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Text:</b>
  <%= @article.text %>
</p>

<p>
  <b>Url:</b>
  <%#= @article.url %>
  <%= link_to truncate(@article.url, length:40), @article.url, {:target => "_blank"} %>
</p>

<p>
  <b>Genre:</b>
  <%#= @article.url %>
	<% if @article.genre != nil %>
  		<%= @article.genre.id %>
	<% else %>
		No entry
	<% end %>
</p>

<p>
  <b>Memos:</b><br />
  <% if @memos.length > 0 %>
  	<% @memos.each_with_index do |memo, i| %>
  		<span style="color: green;">------------</span> 
  						Memo <%= i + 1 %>
		 <span style="color: green;">--------------</span>
		<br />		 
  		<%= memo.text %><br />
  	<% end %>
  <% else %>
  	No memo
  <% end %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>&nbsp;&nbsp;|&nbsp;
<!-- <%#= link_to 'Add memo', new_memo_path, :article_id => @article.id %>&nbsp;&nbsp;|&nbsp; -->
<%= link_to 'Add memo', 
    				:controller => "memos", :action => "new", 
    				:article_id => @article.id %>&nbsp;&nbsp;|&nbsp;
<%= link_to 'Destroy', @article, confirm: 'Are you sure?', method: :delete, style: "color: red;" %>

<!-- <br /> -->
<%#= @memos.class %>
<%#= @memos.length %>
<%#= truncate(@article.url, length:40) %>