config/routes.rb
ResearchHelper2::Application.routes.draw do
  
  get "articles/async_process" => "articles#async_process"
  
  resources :logs

  resources :genres

  resources :memos

  resources :articles

  root :to => "articles#index"
  
  

end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/new
  # GET /logs/new.json
  def new
    @log = Log.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @log = Log.find(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(params[:log])

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.json
  def update
    @log = Log.find(params[:id])

    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity %><br />
    <%= f.text_field :activity %>
  </div>
  <div class="field">
    <%= f.label :memos %><br />
    <%= f.text_area :memos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<div>
	<span class="page_title">
		ログのリスト
	</span>
	
	&nbsp;&nbsp;(<%= link_to 'New Log', new_log_path %>)</div>

<br />

<table>
  <tr>
  	<th>Id</th>
    <th>Activity</th>
    <th>Memos</th>
    <th>Created at</th>
  </tr>

<% @logs.each do |log| %>
  <tr>
  	<td><%= log.id %></td>
    <td><%= link_to log.activity, log %></td>
    <td><%= log.memos %></td>
    <td><%= log.created_at %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Log', new_log_path %>
<!-- <td><%#= log.activity %></td> -->

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Activity:</b>
  <%= @log.activity %>
</p>

<p>
  <b>Memos:</b>
  <%= @log.memos %>
</p>

<p>
  <b>Created at:</b>
  <%= @log.created_at %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>&nbsp;&nbsp;|&nbsp;
<%= link_to 'Destroy', @log, 
			confirm: 'Are you sure?', method: :delete,
			style: "color: red;" %>