config/routes.rb
ResearchHelper2::Application.routes.draw do
  
  get "articles/async_process" => "articles#async_process"
  
  resources :logs

  resources :genres

  resources :memos

  resources :articles

  root :to => "articles#index"
  
  

end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :article
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  # GET /memos
  # GET /memos.json
  def index
    #--------------------------
    # Steps
    # 1. Get sort_type from params
    
    #--------------------------

    #--------------------------
    # 1. Get sort_type from params
    #--------------------------
    @sort_type = params[:sort_type]
    
    if @sort_type == nil
      @sort_type = "id"
    end

    
    # Get memos
    @memos = Memo.find(:all, :order => @sort_type)
    # @memos = Memo.find(:all, :order => "article_id")
    
    # @memos = @memos.sort {|a, b| a.article.genre_id <=> b.article.genre_id}
    # @memos = @memos.sort {|a, b| a.article.genre_id <=> b.article.genre_id}
    
    # @memos = Memo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memos }
    end
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
    @memo = Memo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @memo }
    end
  end

  # GET /memos/new
  # GET /memos/new.json
  def new
    @memo = Memo.new
    
    #
    @article_id = params[:article_id]
    
    if @article_id != nil
      @memo.article_id = @article_id
    end
    
    #-------------------
    # Log
    #-------------------
    @log_message = params[:controller] + "/" + params[:action]
    
    @log = Log.new
    @log.activity = @log_message
    
    if @log.save
      flash[:log_saved] = "Log saved"
      # On "flash" => "黒田・佐藤":124
    else
      flash[:log_saved] = "Log not saved!"
    end
    
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @memo }
    end
  end

  # GET /memos/1/edit
  def edit
    @memo = Memo.find(params[:id])
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(params[:memo])

    # Log --------------------------
    # @log = Log.new
    # @log.memos = params[:controller] + "/" + params[:action] +
                        # #" => " + @memo.id + " : " + @memo.title
                        # " => " + @memo.title
    
    # if @log.save
      # flash[:log_saved] = "Log saved"
      # flash[:log_saved] = @memo.text
      # flash[:log_saved] = "@memo.id => " + @memo.id.to_s
      # On "flash" => "黒田・佐藤":124
    # else
      # flash[:log_saved] = "Log not saved!"
    # end
    
    #/ Log --------------------------

    respond_to do |format|
      if @memo.save
        
        # Log --------------------------
        @log = Log.new
        @log.memos = params[:controller] + "/" + params[:action] +
                            # " => " + @memo.id + " : " + @memo.text
                            # " => " + @memo.title
                            " => " + @memo.id.to_s + " : " + @memo.text
        
        if @log.save
          flash[:log_saved] = "Log saved"
          # flash[:log_saved] = @memo.text
          # flash[:log_saved] = "@memo.id => " + @memo.id.to_s
          # On "flash" => "黒田・佐藤":124lse
        else
          flash[:log_saved] = "Log not saved!"
        end
        
        #/ Log --------------------------
        # Log
        # flash[:log_saved] = @memo.title
        # flash[:log_saved] = "@memo.id => " + @memo.id.to_s
        
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render json: @memo, status: :created, location: @memo }
      else
        format.html { render action: "new" }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memos/1
  # PUT /memos/1.json
  def update
    @memo = Memo.find(params[:id])

    respond_to do |format|
      if @memo.update_attributes(params[:memo])
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy

    respond_to do |format|
      format.html { redirect_to memos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= form_for(@memo) do |f| %>
  <% if @memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.number_field :article_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<!-- <h1>Listing memos</h1>&nbsp; -->

<div>
	<span class="page_title">
		メモのリスト
	</span>
	
	&nbsp;&nbsp;(<%= link_to 'New Memo', new_memo_path %>)</div>

<br />

<table>
  <tr>
  	<th>Id</th>
    <th>Text</th>
    <th>Url</th>
    <th>Article</th>
    <th>Genre</th>
  </tr>

<% @memos.each do |memo| %>
  <tr>
  	<td><%= memo.id %></td>
  	<td><%= link_to truncate(memo.text, length: 40), memo %></td>
  	
  	<% if memo.url.length != 0 %>
  		<td><%= link_to "Go", memo.url %></td>
  	<% else %>
  		<td>No data</td>
  	<% end %>
  	
  	<% if memo.article != nil %>
  		<td class="col_memo_center"><%= memo.article.title %>(<%= memo.article_id %>)</td>
  	<% else %>
  		<td>No data</td>
  	<% end %>
  	
  	<% if memo.article != nil and  memo.article.genre != nil %>
  		<td><%= memo.article.genre.name %>(<%= memo.article.genre.id %>)</td>
  	<% else %>
  		<td>No data</td>
  	<% end %>

  	
  </tr>
<% end %>


</table>

app/views/memos/index~problem.html.erb
<!-- <h1>Listing memos</h1>&nbsp; -->

<div>
	<span class="page_title">
		Memo list
	</span>
	
	&nbsp;&nbsp;(<%= link_to 'New Memo', new_memo_path %>)</div>

<br />

<table>
  <tr>
  	<th>Id</th>
    <th>Text</th>
    <th>Url</th>
    <th>Article</th>
    <th>Genre</th>
  </tr>

<% @memos.each do |memo| %>
  <tr>
  	<td><%= memo.id %></td>
<!--     <td><%#= link_to memo.text, memo %></td> -->
    <td><%= link_to truncate(memo.text, length:40), memo %></td>
    <td><%= link_to "Go", memo.url %></td>
    <td class="col_memo_center"><%= memo.article.title %>(<%= memo.article_id %>)</td>
    <td><%= memo.article.genre.name %>(<%= memo.article.genre.id %>)</td>
  </tr>
<% end %>
</table>

<br />

app/views/memos/new.html.erb
<%= flash[:log_saved] %>

<h1>New memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

<hr />
@article_id => <%= @article_id %><br />

<%# @log_message = params[:controller] + "/" + params[:action] %>
@log_message => <%= @log_message %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= flash[:log_saved] %></p>

<p>
  <b>Text:</b>
  <%= @memo.text %>
</p>

<p>
  <b>Url:</b>
	<% if @memo.url.length > 0 %>
  		<%= link_to truncate(@memo.url, length:40), @memo.url, {:target => "_blank"} %>
	<% else %>
		No entry
	<% end %>
</p>

<p>
  <b>Article:</b>
	<% if @memo.article != nil %>  
		<%= link_to @memo.article.title, @memo.article %>&nbsp;(id=<%= @memo.article_id %>)
	<% else %>
		No entry
	<% end %>
</p>


<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>&nbsp;&nbsp;|&nbsp;
<%= link_to 'Destroy', @memo, 
			confirm: 'Are you sure?', method: :delete,
			style: "color: red;" %>