config/routes.rb
ResearchHelper2::Application.routes.draw do
  
  get "articles/async_process" => "articles#async_process"
  
  resources :logs

  resources :genres

  resources :memos

  resources :articles

  root :to => "articles#index"
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResearchHelper2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <%= javascript_include_tag "/basics" %>
  
  <meta name="viewport"
           content="width=device-width,
           　　　　　　　　　　　  　user-scalable=yes,
          　　　　　　　　　　　  　 initial-scale=2.0,
                    maximum-scale=3.0" />
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	
	
	<script type="text/javascript">
		//REF=> http://semooh.jp/jquery/api/ajax/jQuery.ajax/options/
		function test1() {
			$.ajax({
				// type: "POST",
				type: "GET",
				url: "articles/async_process",
				success: function(msg) {
					alert(msg);
					
					$('#async').html("<b>" + msg + "</b>");
				}
			});
			// $('#async').html("<b>YES</b>");
			
			// alert("yes");
		}
		
		// function test2() {
			// alert("test2");
		// }
	</script>
	
	
	<script type="text/javascript">
		$(function() {
			$('dl.accordion>dd').hide();
			// $('dl.accordion>dt.opened').nextUntil('dl.accordion>dt').show('fast');
			$('dl.accordion>dt.opened').nextUntil('dl.accordion>dt').show();
			$('dl.accordion>dt').click(function(e) {
				$(this).toggleClass('opened');
				// $(this).nextUntil('dl.accordion>dt').toggle('fast');
				$(this).nextUntil('dl.accordion>dt').toggle();
			});
			
			
			//  Open only one item at a time
			// $('dl.accordion>dd').hide();
			// $('dl.accordion>dt.opened').nextUntil('dl.accordion>dt').show('slow');
			// $('dl.accordion>dt').click(function(e) {
				// $('dl.accordion>dd').hide();
				// $('dl.accordion>dt').removeClass('opened');
				// $(this).toggleClass('opened');
				// $(this).nextUntil('dl.accordion>dt').toggle('slow');
			// });
			
			
			// $('dl.accordion').hide();
// 			
			// $('dl.accordion').click(function(e){
				// // $(this).toggleClass('opened');
				// $(this).show('slow');
			// });
			// $('dl.accordion').accordion();
		});		
	</script>
	
</head>
<body>

<%= yield %>

<hr />
	<%= link_to_unless_current "Articles", articles_path %>&nbsp;|&nbsp;
	<%= link_to_unless_current "Memos", memos_path %>&nbsp;|&nbsp;
	<%= link_to_unless_current "Genres", genres_path %>&nbsp;&nbsp;|&nbsp;
	<%= link_to_unless_current "Logs", logs_path %>
<hr />

</body>
</html>